# Generated by Django 4.0.4 on 2022-05-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentindianmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/current'),
        ),
        migrations.AddField(
            model_name='customandtraditionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/tradition'),
        ),
        migrations.AddField(
            model_name='factblogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/fact'),
        ),
        migrations.AddField(
            model_name='freedomfightermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/freedom'),
        ),
        migrations.AddField(
            model_name='historicalplacemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/historical'),
        ),
        migrations.AddField(
            model_name='indianhistorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image/history'),
        ),
    ]
