# Generated by Django 4.0.4 on 2022-05-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_currentindianmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IndianHistoryComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indianhistorycomments', to='MainApp.indianhistorymodel')),
            ],
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='HistoricalPlaceComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicalplacecomments', to='MainApp.historicalplacemodel')),
            ],
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='FreedomFighterComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freedomfightercomments', to='MainApp.freedomfightermodel')),
            ],
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='FactBlogComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factblogcomments', to='MainApp.factblogmodel')),
            ],
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CustomeAndTraditionComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custromandtraditioncomments', to='MainApp.customandtraditionmodel')),
            ],
            bases=('MainApp.comments',),
        ),
        migrations.CreateModel(
            name='CurrentIndiaComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentindiancommetns', to='MainApp.currentindianmodel')),
            ],
            bases=('MainApp.comments',),
        ),
    ]
