# Generated by Django 4.0.4 on 2022-05-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_comments_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentindiacomments',
            options={'verbose_name_plural': 'CurrentIndiaComments'},
        ),
        migrations.AlterModelOptions(
            name='currentindianmodel',
            options={'verbose_name_plural': 'CurrentIndianModel'},
        ),
        migrations.AlterModelOptions(
            name='customandtraditionmodel',
            options={'verbose_name_plural': 'CustomandTraditionModel'},
        ),
        migrations.AlterModelOptions(
            name='customeandtraditioncomments',
            options={'verbose_name_plural': 'CustomeAndTraditionComments'},
        ),
        migrations.AlterModelOptions(
            name='factblogcomments',
            options={'verbose_name_plural': 'FactBlogComments'},
        ),
        migrations.AlterModelOptions(
            name='factblogmodel',
            options={'verbose_name_plural': 'FactBlogModel'},
        ),
        migrations.AlterModelOptions(
            name='freedomfightercomments',
            options={'verbose_name_plural': 'FreedomFighterComments'},
        ),
        migrations.AlterModelOptions(
            name='freedomfightermodel',
            options={'verbose_name_plural': 'FreedomFighterModel'},
        ),
        migrations.AlterModelOptions(
            name='historicalplacecomments',
            options={'verbose_name_plural': 'HistoricalPlaceComments'},
        ),
        migrations.AlterModelOptions(
            name='historicalplacemodel',
            options={'verbose_name_plural': 'HistoricalPlaceModel'},
        ),
        migrations.AlterModelOptions(
            name='indianhistorycomments',
            options={'verbose_name_plural': 'IndianHistoryComments'},
        ),
        migrations.AlterModelOptions(
            name='indianhistorymodel',
            options={'verbose_name_plural': 'IndianHistoryModel'},
        ),
    ]
