# Generated by Django 4.0.4 on 2022-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_currentindiacomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentindianmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customandtraditionmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='factblogmodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='freedomfightermodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalplacemodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='indianhistorymodel',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
