# Generated by Django 4.0.4 on 2022-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_currentindianmodel_desc_customandtraditionmodel_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentindianmodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customandtraditionmodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='factblogmodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='freedomfightermodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalplacemodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='indianhistorymodel',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
    ]
