# Generated by Django 4.0.4 on 2022-05-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_currentindianmodel_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentindianmodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='customandtraditionmodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='factblogmodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='freedomfightermodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='historicalplacemodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='indianhistorymodel',
            name='desc',
        ),
    ]
