# Generated by Django 4.0.4 on 2022-05-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_historicalplacemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAndTraditionComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.comments')),
            ],
            options={
                'verbose_name_plural': 'CustomAndTraditionComments',
            },
            bases=('MainApp.comments',),
        ),
        migrations.AlterModelOptions(
            name='currentindianmodel',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'CurrentIndianModel'},
        ),
        migrations.AlterModelOptions(
            name='customandtraditionmodel',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'CustomandTraditionModel'},
        ),
        migrations.AlterModelOptions(
            name='factblogmodel',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'FactBlogModel'},
        ),
        migrations.AlterModelOptions(
            name='freedomfightermodel',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'FreedomFighterModel'},
        ),
        migrations.AlterModelOptions(
            name='indianhistorymodel',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'IndianHistoryModel'},
        ),
        migrations.DeleteModel(
            name='CustomeAndTraditionComments',
        ),
        migrations.AddField(
            model_name='customandtraditioncomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customandtraditioncomments', to='MainApp.customandtraditionmodel'),
        ),
    ]
