# Generated by Django 4.0.4 on 2022-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_customandtraditioncomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentindianmodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customandtraditionmodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='factblogmodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freedomfightermodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalplacemodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indianhistorymodel',
            name='viewcounter',
            field=models.IntegerField(default=0),
        ),
    ]
