# Generated by Django 4.0.4 on 2022-05-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_currentindianmodel_viewcounter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentindianmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='indianhistorymodel',
            name='image',
        ),
    ]
