# Generated by Django 4.0.4 on 2022-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_currentindianmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide/image')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('link', models.URLField()),
            ],
        ),
    ]
