# Generated by Django 4.0.4 on 2022-06-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_slideimgae'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideImgae',
            new_name='SlideImage',
        ),
    ]
