# Generated by Django 4.0.4 on 2022-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_remove_indianhistorycomments_comments_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentindianmodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customandtraditionmodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='factblogmodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='freedomfightermodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalplacemodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='indianhistorymodel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
