# Generated by Django 4.0.4 on 2022-06-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_indianhistorycomments_currentindiacomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='indianhistorymodel',
            name='type',
            field=models.CharField(choices=[('ANCIENT', 'ANCIENT'), ('MIDDLE', 'MIDDLE'), ('MODERN', 'MODERN')], default='ANCIENT', max_length=100),
        ),
    ]
